# Generated by Django 2.2.1 on 2019-05-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=56)),
                ('esal', models.IntegerField()),
                ('eaddr', models.IntegerField()),
            ],
        ),
    ]
